### ISSUE TITLE
Not able to convert and apply filter on spec.md

### ISSUE THREAD

**Issue by pbt001** [aaren/pandoc-reference-filter#23]
Hi, 

when I try to convert documents with e.g. `pandoc spec.md --filter internal-references --to latex` I get the following:

> Traceback (most recent call last):
>   File "/usr/local/bin/internal-references", line 9, in <module>
>     load_entry_point('pandoc-internal-references==0.5.1', 'console_scripts', 'internal-references')()
>   File "build/bdist.macosx-10.12-intel/egg/internalreferences.py", line 527, in main
> KeyError: 0
> pandoc: Error running filter internal-references
> Filter returned error status 1

Can this issue be resolved?

**Comment by cpandar** [comment]
I am not at all an expert here, but-

I am running into the same "KeyError: 0" issue, and I believe it is caused by outdated syntax for how pandocfilters is being used. I.e., in line 527 of internalreferences.py, it says:

`metadata = doc[0]['unMeta']`

I believe the following is now more appropriate:

```
if 'meta' in doc:
    metadata = doc['meta']
elif doc[0]:  # old API
    metadata = doc[0]['unMeta']
else:
    metadata = {}
```

I implemented that change, and then run into other errors, so I gave up. But I believe the above fixes the specific "KeyError: 0" issue.
